### ISSUE TITLE
Feature Overlay with large number of cells

### ISSUE THREAD

**Issue by Nuwah12** [schwartzlab-methods/too-many-cells-interactive#6]
Hi all, thanks for developing such an awesome tool. 
Our lab has implemented `too-many-cells-interactive` as part of our new data visualization tools on the HPAP repository. While testing the feature overlay option, we noticed the behavior to be a bit inconsistent. Here is a list of problems / behaviors we are observing:

* Dropdown menu fails to appear under 'Single Lookup', and submitting a gene name results in the loading message appearing, and quickly disappearing with no change in output. (I had it working, but I have since been unable to replicate the behavior).
* Bulk lookup appears to work, but is only feasible for genes in a low number of cells. Selecting a gene which is expressed in a higher number of cells makes the program load seemingly forever.

Something to consider is the size of the dataset - about 220,000 cells. This seems quite large, especially since the examples in your docs use ~18,000 cells. This seems like the most obvious cause to me.

Any other ideas and help are greatly appreciated :smiley:

**Comment by Nuwah12** [comment]
Apparently there was some confusion, so I'll try to clear things up:

The genes that we seem to be having trouble with are genes that are **expressed in a high number of cells**. Genes that serve as markers for rare cell types, that is, **genes expressed in a low number of cells** seem to be working with the feature overlay.

**Comment by cklamann** [comment]
Thanks for submitting this issue.

If I understand correctly, there are two problems:

1. The autocomplete choices are slow to load (if they load at all), effectively disabling single-gene lookup for large datasets.

2. When genes expressed in a high number of cells are selected for overlay, the program hangs.

I can get working on 1) in the next few (business) days, as I think it can be mitigated by improving the database indexing for faster searches.

2) might be a little trickier, as we may be reaching the limit of what the browser can handle, but I'll need to take a closer look before I know what's going on.

**Comment by cklamann** [comment]
#8 should take care of the autocomplete issue. Please see the [release notes](https://github.com/schwartzlab-methods/too-many-cells-interactive/releases/tag/v0.2.0-beta) for important information about breaking changes before pulling in the new code. I am going to close this issue and move the discussion about large datasets to its own thread (#9).
